remove run test
=> a test at compile time is for us enough

diff --git a/external/bsd/mdocml/dist/configure b/external/bsd/mdocml/dist/configure
--- a/external/bsd/mdocml/dist/configure
+++ b/external/bsd/mdocml/dist/configure
@@ -24,8 +24,9 @@ CFLAGS="${CFLAGS} -Wno-unused -Werror"
 runtest() {
 	echo ${CC} ${CFLAGS} -o test-${1} ${SRCDIR}/test-${1}.c 1>&2
 	${CC} ${CFLAGS} -o "test-${1}" "${SRCDIR}/test-${1}.c" 1>&2 || return 0
-	"./test-${1}" && echo "#define HAVE_${2}" \
-		|| echo FAILURE: test-${1} returned $? 1>&2
+	echo "#define HAVE_${2}"
+	#"./test-${1}" && echo "#define HAVE_${2}" \
+	#	|| echo FAILURE: test-${1} returned $? 1>&2
 	rm "test-${1}"
 }
 
